<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.22000.0</TargetFramework>
    <UseWinUI>true</UseWinUI>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>preview</LangVersion>
    <WindowsPackageType>None</WindowsPackageType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hpp.Application\Hpp.Application.csproj" />
    <ProjectReference Include="..\Hpp.Domain\Hpp.Domain.csproj" />
    <ProjectReference Include="..\Hpp.Infrastructure\Hpp.Infrastructure.csproj" />
    <ProjectReference Include="..\Hpp.Shared\Hpp.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.8.260101001" />
    <PackageReference Include="CommunityToolkit.WinUI.Controls" Version="8.0.0" />
    <PackageReference Include="CommunityToolkit.WinUI.Controls.DataGrid" Version="8.0.0" />
    <PackageReference Include="CommunityToolkit.WinUI.UI" Version="8.0.0" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.2" />
  </ItemGroup>
</Project>
