<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.22000.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Hpp.Application\Hpp.Application.csproj" />
    <ProjectReference Include="..\..\src\Hpp.Domain\Hpp.Domain.csproj" />
    <ProjectReference Include="..\..\src\Hpp.Infrastructure\Hpp.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Hpp.WinUI\Hpp.WinUI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.2" />
  </ItemGroup>
</Project>
